some clean up

diff --git a/bin/gng b/bin/gng
--- a/bin/gng
+++ b/bin/gng
@@ -1,119 +1,160 @@
 #!/usr/bin/env bash
-
-DEBUG="${DEBUG:-0}"
-if [[ "${DEBUG}" = 1 ]]; then
-    set -x
-fi
-
-set -e
+set -o errexit
+set -o nounset
 set -o pipefail
-# DEFAULTS may be overridden by calling environment.
-GRADLE="${GRADLE:-gradle}"
-GRADLEW="${GRADLEW:-gradlew}"
-GRADLE_BUILDFILE="${GRADLE_BUILDFILE:-build.gradle}"
-GRADLE_KTS_BUILDFILE="${GRADLE_KTS_BUILDFILE:-build.gradle.kts}"
+set -o errtrace
+DEBUG="${DEBUG:-0}"
+if [[ "${DEBUG}" == 1 ]]; then
+  set -x
+fi
+export SHELLOPTS
 
-die() {
-    echo -e "${@}" >&2
-    exit 1
+readonly INFO_COLOR='\033[1;96m'
+readonly NO_COLOR='\033[0m' # No Color
+readonly ERROR_COLOR='\033[0;31m'
+
+err() {
+  echo -e "${ERROR_COLOR}$*${NO_COLOR}" >&2
 }
 
-lookup() {
-    local file="${1}"
-    local curr_path="${2}"
-    [[ -z "${curr_path}" ]] && curr_path="${PWD}"
+info() {
+  echo -e "${INFO_COLOR}$*${NO_COLOR}"
+}
 
-    # Search recursively upwards for file.
-    until [[ "${curr_path}" == "/" ]]; do
-        if [[ -e "${curr_path}/${file}" ]]; then
-            echo "${curr_path}/${file}"
-            break
-        else
-            curr_path=$(dirname "${curr_path}")
-        fi
+die() {
+  local exit_status=$?
+  err "$@" "($(caller))"
+  if [ "$exit_status" = "0" ]; then
+    exit 1
+  else
+    exit $exit_status
+  fi
+}
+
+__errorCallBack__() {
+  local exit_status=$?
+  local trace_info
+  trace_info=$(
+    local frame=0
+    while caller ${frame}; do
+      ((frame++))
     done
+  )
+  err "ErrorStack =>
+${trace_info}"
+  exit $exit_status
+}
+trap '__errorCallBack__' ERR
+
+# DEFAULTS may be overridden by calling environment.
+readonly GRADLE="${GRADLE:-gradle}"
+readonly GRADLEW="${GRADLEW:-gradlew}"
+readonly GRADLE_BUILDFILE="${GRADLE_BUILDFILE:-build.gradle}"
+readonly GRADLE_KTS_BUILDFILE="${GRADLE_KTS_BUILDFILE:-build.gradle.kts}"
+
+lookup() {
+  local file="${1}"
+  local curr_path="${2}"
+  [[ -z "${curr_path}" ]] && curr_path="${PWD}"
+
+  # Search recursively upwards for file.
+  until [[ "${curr_path}" == "/" ]]; do
+    if [[ -e "${curr_path}/${file}" ]]; then
+      echo "${curr_path}/${file}"
+      break
+    else
+      curr_path=$(dirname "${curr_path}")
+    fi
+  done
+}
+
+__GRADLE_HOME__=$(mktemp -d)
+trap 'rm -rf ${__GRADLE_HOME__}' EXIT
+#Embedded Gradle Wrapper
+function __gradlew__() {
+  java -classpath /opt/gng/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain \
+    -q --no-daemon -g "${__GRADLE_HOME__}" -I "/opt/gng/gradle/init.gradle" "$@"
 }
 
 select_gradle() {
-    local dir="${1}"
-
-    # Use project's gradlew if found.
-    local gradlew=$(lookup "${GRADLEW}" "${dir}")
-    if [[ -z "${gradlew}" ]]; then
-        die "No ${GRADLEW} set up for this project; Please use 'gng --bootstrap \${version}'."
-    else
-        echo "${gradlew}"
-        return 0
-    fi
-
+  local dir="${1}"
+  # Use project's gradlew if found.
+  local gradlew
+  gradlew=$(lookup "${GRADLEW}" "${dir}")
+  if [[ -z "${gradlew}" ]]; then
+    err "No ${GRADLEW} set up for this project; Please use 'gng --bootstrap' installing a Gradle Wrapper'."
     return 1
+  else
+    echo "${gradlew}"
+    return 0
+  fi
+
+  return 1
 }
 
-execute_gradle() {
-    local build_gradle=$(lookup "${GRADLE_BUILDFILE}")
-    local build_gradle_kts=$(lookup "${GRADLE_KTS_BUILDFILE}")
-    local gradle=$(select_gradle)
-
-    if [[ -n "${build_gradle}" ]] || [[ -n "${build_gradle_kts}" ]]; then
-        local ktsDirName="$(dirname "${build_gradle_kts}")"
-        local dirName="$(dirname "${build_gradle}")"
-        if ((${#ktsDirName} > ${#dirName}))
-        then
-            build_gradle=${build_gradle_kts}
-        fi
-        # We got a good build file, start gradlew there.
-        cd "$(dirname "${build_gradle}")"
-    else
-        die "Unable to find a gradle build file named ${GRADLE_BUILDFILE} or ${GRADLE_KTS_BUILDFILE}."
-    fi
-
-    # Say what we are gonna do, then do it.
-    echo "Using gradle at '${gradle}' to run buildfile '${build_gradle}'"
-    "${gradle}" "$@"
+gradle() {
+  local gradle
+  gradle=$(select_gradle "${PWD}")
+  # Say what we are gonna do, then do it.
+  info "Using gradle at '${gradle}' to run\n"
+  "${gradle}" "$@"
 }
 
 function install() {
-    local saved_params=()
-    local gradle_version="latest"
-    local distType="bin"
-    if [[ $# -gt 0 ]]; then
-        gradle_version="$1"
-        shift
-    fi
-    if [[ $# -gt 0 ]]; then
-        distType="$1"
-        shift
-    fi
-    case "${distType}" in
-    "all"|"bin")
-    ;;
-    *)
+  local saved_params=()
+  local gradle_version="latest"
+  local distType="bin"
+  if [[ $# -gt 0 ]]; then
+    gradle_version="$1"
+    shift
+  fi
+  if [[ $# -gt 0 ]]; then
+    distType="$1"
+    shift
+  fi
+  case "${distType}" in
+  "all" | "bin") ;;
+
+  *)
     die "wrong distType: ${distType}(all, bin)"
     ;;
-    esac
+  esac
 
-    if [[ "${gradle_version}" = "latest" ]]; then
-        echo "Fetching the latest Gradle version"
-        local gradle_version_info=$(curl -sSL "https://services.gradle.org/versions/current")
-        gradle_version=$(echo "$gradle_version_info" | python -c "import json,sys;obj=json.load(sys.stdin);print obj['version'];")
-    fi
+  if [[ "${gradle_version}" == "latest" ]]; then
+    info "Fetching the latest Gradle version"
+    local gradle_version_info
+    gradle_version_info=$(curl -sSL "https://services.gradle.org/versions/current")
+    gradle_version=$(echo "$gradle_version_info" | python -c "import json,sys;obj=json.load(sys.stdin);print obj['version'];")
+  fi
 
-
-    local gradle_home=$(mktemp -d)
-    trap 'rm -rf ${gradle_home}' EXIT
-    echo "Running the embedded wrapper ..."
-    java -classpath /opt/gng/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain  \
- -q -g "${gradle_home}" -I "/opt/gng/gradle/init.gradle"  \
- --no-daemon -Pver=${gradle_version} -PdistType=${distType} wrapper
-    # Clean the temporary cache dir
-    rm -rf .gradle
+  info "Running the embedded wrapper ..."
+  __gradlew__ -Pver="${gradle_version}" -PdistType="${distType}" wrapper
+  # Clean the temporary cache dir
+  rm -rf .gradle
 }
 
-if [[ "--bootstrap" = "$1" ]]; then
-    which java > /dev/null 2>&1 || die "ERROR: no 'java' command could be found in your PATH."
-    shift
-    install "$@"
-else
-    execute_gradle "$@"
-    exit $?
-fi
+#Support `gradle init` behavior
+init() {
+  info "Initializing a Gradle project ..."
+  local gradle
+  gradle=$(select_gradle)
+  if [[ -z ${gradle} ]]; then
+    install
+    gradle=$(select_gradle)
+  fi
+  "${gradle}" "$@"
+}
+
+case "$1" in
+--bootstrap)
+  command -v java >/dev/null 2>&1 || die "ERROR: no 'java' command could be found in your PATH."
+  shift
+  install "$@"
+  ;;
+init)
+  init "$@"
+  ;;
+*)
+  gradle "$@"
+  ;;
+esac
