Directly copy Gradle Wrapper instead of running wrapper task

diff --git a/bin/gng b/bin/gng
--- a/bin/gng
+++ b/bin/gng
@@ -21,7 +21,6 @@ source "${SELF_DIR}/common.sh" || {
   echo "Failed to load common.sh in ${SELF_DIR}"
   exit 1
 }
-info "SOURCE: ${SOURCE}, $0"
 # DEFAULTS may be overridden by calling environment.
 readonly GRADLEW="${GRADLEW:-gradlew}"
 
@@ -71,19 +70,31 @@ function __install_gw() {
     local type="${2}"
     local mirrorUrl="${3}"
     local dir="${4}"
-    info "Installing/Upgrading Gradle Wrapper in ${dir}. (version=${version}, distributionType=${type}, mirrorUrl=${mirrorUrl})"
     [ -d "${dir}" ] || mkdir "${dir}"
-    cd "${dir}" || die "Failed to change to directory ${dir}"
-    mkdir -p "gradle/wrapper"
+    mkdir -p "${dir}/gradle/wrapper"
+
+    info "Installing Gradle Wrapper in ${dir}. (version=${version}, distributionType=${type}, mirrorUrl=${mirrorUrl:-<Not Specified>})"
+
     #Copy the embedded Gradle Wrapper
-    local distributionUrl="https://${mirrorUrl:-services.gradle.org/distributions}"
+    local srcDir="${SELF_DIR}/.."
+    cp -f "${srcDir}/gradle/gng.cfg" "${dir}/gradle/"
+    cp -f "${srcDir}/gradle/gradlew" "${dir}/"
+    cp -f "${srcDir}/gradle/gradlew.bat" "${dir}/"
+    cp -f "${srcDir}/gradle/wrapper/gradle-wrapper.jar" "${dir}/gradle/wrapper/"
+
+    local distributionUrl="${mirrorUrl:-https://services.gradle.org/distributions}"
+    # shellcheck disable=SC2001
+    #Escape characters, see java.util.Properties.saveConvert for details
+    distributionUrl=$(echo "${distributionUrl}" | sed 's/[#\!=:]/\\&/g') || die "Failed to escape characters in distributionUrl(${distributionUrl}"
     distributionUrl="${distributionUrl}/gradle-${version}-${type}.zip"
-    for f in "gradle/wrapper/gradle-wrapper.jar" "gradle/gradlew" "gradle/gradlew.bat"; do
-      cp -f "${SELF_DIR}/../${f}" "${PWD}/${f}"
-    done
-    java -DdistributionUrl="${distributionUrl}" -cp "${SELF_DIR}/gradle" GenerateWrapperProperties >"gradle/wrapper/gradle-wrapper.properties"
-    cp -f "${SELF_DIR}/gng.cfg" "gradle/"
-    rm -rf .gradle
+    cat <<__TEXT__ >"${dir}/gradle/wrapper/gradle-wrapper.properties"
+#Generated by GNG
+distributionBase=GRADLE_USER_HOME
+distributionPath=wrapper/dists
+distributionUrl=${distributionUrl}
+zipStoreBase=GRADLE_USER_HOME
+zipStorePath=wrapper/dists
+__TEXT__
   ) || die "Failed to install Gradle Wrapper!"
 }
 
@@ -93,7 +104,7 @@ select_gradle() {
   local gradlew
   gradlew=$(lookup "${GRADLEW}" "${dir}")
   if [[ -z "${gradlew}" ]]; then
-    die "No ${GRADLEW} set up for this project; Please use 'gng bootstrap' installing a Gradle Wrapper'."
+    die "No ${GRADLEW} set up for this project; Please use 'gng wrapper' installing a Gradle Wrapper'."
   else
     echo "${gradlew}"
     return 0
@@ -120,9 +131,11 @@ gradle() {
 bootstrap_help() {
   printf '%s\n' "Generates a Gradle Wrapper"
   printf 'Usage: gng wrapper [-v|--version <arg>] [-t|--distribution-type <arg>] [-m|--mirror <arg>] [-h|--help] [ -d|--destination-dir <arg>\n'
-  printf '\t%s\n' "-v, --version: Gradle Version (default: 'latest')"
+  printf '\t%s\n' "-v, --version: Gradle Version (default: 'latest', version information is from https://services.gradle.org/versions/current, visit https://services.gradle.org/versions/all for all available versions)"
   printf '\t%s\n' "-t, --distribution-type: Gradle Distribution Type (default: 'all')"
-  printf '\t%s\n' "-m, --mirror: Gradle Distribution Mirror Site (no default)"
+  printf '\t%s\n' "-m, --mirror: Gradle Distribution Mirror URL Prefix(Optional with no default value, The url prefix replaces https://services.gradle.org/distributions/)"
+  printf '\t%s\n' "              It replaces the whole distributionUrl except the file part in a URL. For example, if specify '-m \"https://example.com/gradle/\"', then"
+  printf '\t%s\n' "              \"https://services.gradle.org/distributions/gradle-6.8-all.zip\" will become \"https://example.com/gradle/gradle-6.8-all.zip\""
   printf '\t%s\n' "-d, --destination-dir : The folder location where generated Gradle Wrapper(default: 'Your current working directory retrieved using \${PWD}')"
   printf '\t%s\n' "-h, --help: Prints help"
 }
